### ISSUE TITLE
`Cannot find merlin binary at "ocamlmerlin"` while ocamlmerlin is in PATH

### ISSUE THREAD

**Issue by mickaelistria** [freebroccolo/ocaml-language-server#122]
I'm trying to create a Docker image that runs this language server. Here is the Dockerfile

```Dockerfile
FROM fedora:27
RUN dnf install -y redhat-rpm-config patch unzip which m4 ocaml opam npm
RUN opam init -y && opam install -y merlin
RUN npm install -g ocaml-language-server
ENV PATH="${PATH}:/root/.opam/default/bin"
#ENTRYPOINT [ "ocaml-language-server" ]
```

You can see merlin installed (line 3) and added to PATH (line 5).
Running this image (previously built locally as `caml-language-server`) with `docker run -i caml-language-server which ocamlmerlin` returns the expected and resolved path `/root/.opam/default/bin/ocamlmerlin` and similarly, running `docker run -i caml-language-server ocamlmerlin` doesn't fail. So it seems like ocamlmerlin is available in the PATH and accessible.

However, when I do `docker run -i caml-language-server ocaml-language-server --stdio` to start the server, then I get an error on first interaction:
```
Content-Length: 152

{"jsonrpc":"2.0","id":0,"method":"window/showMessageRequest","params":{"type":2,"message":"Cannot find merlin binary at \"ocamlmerlin\".","actions":[]}}Content-Length: 201

{"jsonrpc":"2.0","id":1,"method":"window/showMessageRequest","params":{"type":2,"message":"Double check your path or try configuring \"reason.path.ocamlmerlin\" under \"User Settings\".","actions":[]}}/usr/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:34
                throw error;
                ^

Error: spawn ocamlmerlin ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Is there anything specific necessary for the LS to resolve ocamlmerlin additonally to placing it in PATH ?

**Comment by freebroccolo** [comment]
> Is there anything specific necessary for the LS to resolve ocamlmerlin additonally to placing it in PATH ?

Sorry for the late response to this.

Briefly, the problem here has to do with the changes "opam init" makes to the shell init scripts and when those changes are active for a given shell session. I don't have a development environment handy to double check at the moment, but IIRC, on Linux with bash the OPAM environment will only be initialized properly for login shells.

One possible way to work around this issue, without launching `ocaml-language-server` through an interactive shell, would be to use `opam config exec ocaml-language-server`.

Unfortunately there's not much I can do to make this more automatic as long as the intention is that the tooling is installed and managed through OPAM.
