### ISSUE TITLE
Integrate with BetterErrors

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/ocaml-language-server#17]

**Comment by jchavarri** [comment]
@freebroccolo I'd be interested in helping with this, if nobody else has claimed it. I've been able to set up the environment, but quickly ran into a couple of things:

- How do you set up the dev environment in vscode? I cloned both the extension and this repo, and managed to get the debugger running for the client / extension, but i haven't been able to use the "attach process" approach explained in the [vscode docs](https://code.visualstudio.com/docs/extensions/example-language-server) for the server. I always get timeouts and the `Debugging with legacy protocol because Node.js version could not be determined` error.

- How would this integration look like at a high level? @chenglou mentioned in Discord:

> Well you'd probably want another mode in super errors actually
Naive string parsing won't work well especially for type mismatch where the types are big
And you certainly don't want the ASCII editor from super errors in your editor inline error
So it'd be a little like merlin. Gives you back the error in json

From that, I understand a new file `bsb.ts` should be added to `src/server/processes/`, and this integration would also require changing https://github.com/BuckleScript/bucklescript/tree/master/jscomp/super_errors so there's a new flag `-bs-super-errors-lsp` or something similar to return the results as json instead of string, right?

Does that make sense?

**Comment by freebroccolo** [comment]
> How do you set up the dev environment in vscode? I cloned both the extension and this repo, and managed to get the debugger running for the client / extension, but i haven't been able to use the "attach process" approach explained in the vscode docs for the server. I always get timeouts and the Debugging with legacy protocol because Node.js version could not be determined error.

It's been awhile since I tried to run the server in debug mode but I know that it did work at one point and I believe the setup was pretty much the same as how it is described in the vscode docs for the example language server thing.

What might be going on is that some of the project settings under the `.vscode` directory might be out of date and that might be causing problems getting the debugging connection set up. I know that over the last several releases of vscode, some of those settings have changed, but I haven't gone through and made sure everything is up to date.

I will try to take a look at that soon but in the meantime you might try looking through the files in that directory and comparing to a freshly generated extension or comparing to whatever is discussed in the current vscode docs.

> How would this integration look like at a high level? @chenglou mentioned in Discord:

I'm actually not sure what is best here at the moment, partly because I haven't looked closely at the super errors stuff you are referencing. Generally speaking, working with JSON is nicer, but complex parsing isn't really a problem because I'm already doing that in several places in the server for other stuff. Writing a chevrotain parser for types would not be particularly difficult. But if additional parsing and processing can be avoided that would be nice.

> From that, I understand a new file bsb.ts should be added to src/server/processes/, and this integration would also require changing https://github.com/BuckleScript/bucklescript/tree/master/jscomp/super_errors so there's a new flag -bs-super-errors-lsp or something similar to return the results as json instead of string, right?
> 
> Does that make sense?

Yes, I think that makes sense and sounds like it would be a reasonable approach.

**Comment by chenglou** [comment]
Outputting json might be slightly tricky,. It in the worst case I can output an easy to parse format.
Glad to see this picked up!

**Comment by jchavarri** [comment]
> you might try looking through the files in that directory and comparing to a freshly generated extension or comparing to whatever is discussed in the current vscode docs.

This is a great idea, I actually managed to solve it using that approach, seemed to be a problem upstream (fix in https://github.com/reasonml-editor/vscode-reasonml/pull/99).

Thanks for the pointers, I'm gonna play more to understand better how the protocol works and report back in case I hit any roadblocks.

**Comment by chenglou** [comment]
Done =)
