### ISSUE TITLE
Unknown request method: reason.client.giveWordAtPosition

### ISSUE THREAD

**Issue by RCmerci** [freebroccolo/ocaml-language-server#28]
![image](https://user-images.githubusercontent.com/5608710/28950469-b8cef912-78f6-11e7-92f7-6114565efced.png)

lsp-mode in emacs client.
could it be any config uncorrectly?
 i just copy the config elisp in README to my .emacs.

when i try to complete-symbol, emacs says "Unknown request method: reason.client.givePrefix"

**Comment by RCmerci** [comment]
i found 'reason.client.givePrefix' is ocaml-language-server's private request, is it right?
so i should implement these 'reason.client.X' in emacs client to make it works?

**Comment by freebroccolo** [comment]
Sorry for the late response. Yes, `reason.client` messages are custom messages that the client was expected to respond to. However, they are no longer needed with the development version of the server and will be phased out in the next release.

If you build the server from the `master` branch is should work. Otherwise I am planning to make a new release very soon.

**Comment by arxanas** [comment]
There was a new release as per https://github.com/freebroccolo/ocaml-language-server/issues/23#issuecomment-327957138, so I think this can be closed.
