### ISSUE TITLE
Interface/implementation mismatch errors not reported.

### ISSUE THREAD

**Issue by cristianoc** [freebroccolo/ocaml-language-server#51]
When working on vscode with `"reason.bsb.enabled": true`, this is the flow I'm observing:
1) Rename a function `foo` in the .re file to `foo2`, keep .rei unchanged.
2) Error "does not match the interface..." only reported in the terminal, not in the editor.
3) Rename to `foo2` also in the .rei file.
4) Now follow-on usage errors "value foo2 can't be found" reported both in the terminal and in the editor.

So it seems the issue is specifically for the interface/implementation mismatch error.

**Comment by ccaseiro** [comment]
I have the same problem.

Can reproduce it with only 2 `re` files. It happens with or without `reason.bsb.enabled`.

If I start with:

```
/* File A */
let function1 = () => "hello";
```

```
/* File B */
A.function1();
```

Now, when I rename `function1` to `function2` in both files, the editor marks File B with an error on
```
[merlin] Error: Unbound value A.function2
```
The javascript compilation (`bsb -make-world -w`) in background completes ok and with the function renamed in both `.js` files.
If I `Reload window` on vscode the error disappears.

**Comment by zploskey** [comment]
I tried reproducing this with @ccaseiro in discord and was unsuccessful. The main difference in our setups is that I am on Linux.

**Comment by jchavarri** [comment]
> 2. Error "does not match the interface..." only reported in the terminal, not in the editor.

This part of the issue reported by @cristianoc sounds to me like some output from `bsb` that the `ocaml-lan-server` parser is not able to process. I can look into this.

The other problem reported by @ccaseiro sounds Merlin related, not `bsb`:

> The javascript compilation (`bsb -make-world -w`) in background completes ok and with the function renamed in both .js files

**Comment by jchavarri** [comment]
I was looking to update the `bsb` parser in order to fix this, but it's hard because the error explanation that `bsb` outputs can literally be any string of any number of lines, and right now there's no characters delimiting it.

@chenglou Is there anything that can be done on the `bsb` side to separate the context (that includes the line numbers like `2 | someCode`) and the error itself?

```
   8 ┆ test(
   9 ┆   "one limb number",
  10 ┆   () => expect(Bn.fromFlfdoat(12345.) |> Bn.toString(~base=16)) |> toB
       e("3039")
  11 ┆ );
  12 ┆ test(

  /* SEPARATOR OR ERROR HEADER HERE */

  The value fromFlfdoat can't be found in Bn
  
  Hint: Did you mean fromFloat?
  
ninja: build stopped: subcommand failed.
```

That'd help fixing this issue without increasing the complexity of the regexps.

The output right now for the error mentioned by @cristianoc is:

```
ninja: Entering directory `lib/bs'
[1/2] Building src/Bn.cmj
FAILED: src/Bn.cmj /Users/javi/Development/github/bs-bn.js/lib/js/src/Bn.js 
/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/bs-platform/lib/bsc.exe -bs-package-name bs-bn.js  -bs-package-output commonjs:lib/js/src -bs-assume-has-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include   -I src  -w -30-40+6+7+27+32..39+44+45+101 -nostdlib -I '/Users/javi/Development/github/bs-bn.js/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -bs-re-out -bs-super-errors -o src/Bn.cmj -c  src/Bn.mlast 

  We've found a bug for you!
  /Users/javi/Development/github/bs-bn.js/src/Bn.re
  
  The implementation src/Bn.mlast
       does not match the interface src/bn.cmi:
       The value `toString' is required but not provided
  
ninja: build stopped: subcommand failed.
```

**Comment by freebroccolo** [comment]
> @chenglou Is there anything that can be done on the bsb side to separate the context (that includes the line numbers like `2 | someCode`) and the error itself?

If the error context always consists of lines like that couldn't you match all the lines at once with `/^\d+\s+\|\s+.*$/gm` and then advance the parser to the error message based on the result?

In case it's not so straightforward, I'll just add that I've been planning to rewrite the bsb output parser (and the ocamldoc parser) using [chevrotain](https://github.com/SAP/chevrotain) very soon and maybe it'd be easier to deal with at that point.

The ocamldoc parser currently uses peg.js but there are some corner cases I need to fix there and I'd like to move all of the parsing duties over to chevrotain since it's cleaner and more flexible (I've been using it in another language server with good results).

For the bsb parser, I'd also like it to be able to handle error reports even when the super errors functionality is enabled but last time I checked this produces different output that the current patterns don't seem to match against.
